pipeline {
    agent any

    environment {
        IMAGE_NAME = 'vamshiadep21/mlops-infer'
        TAG = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Clone Repo') {
            steps {
                echo 'Cloning the repository...'
                checkout scm
            }
        }

        stage('Install Python Deps (Optional)') {
            steps {
                sh 'python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Building Docker image: ${IMAGE_NAME}:${TAG}"
                sh "docker build -t ${IMAGE_NAME}:${TAG} ."
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh """
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker tag ${IMAGE_NAME}:${TAG} ${IMAGE_NAME}:${TAG}
                        docker push ${IMAGE_NAME}:${TAG}
                    """
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                echo 'Deploying to Minikube Kubernetes Cluster...'

                sh """
                    # Replace image tag in deployment
                    sed -i 's|image: .*|image: ${IMAGE_NAME}:${TAG}|' k8s/deployment.yaml

                    # Apply deployment and service
                    kubectl apply -f k8s/deployment.yaml
                    kubectl apply -f k8s/service.yaml

                    # Wait for pods to be ready
                    kubectl rollout status deployment/mlops-infer-deployment
                """
            }
        }

        stage('Access App') {
            steps {
                echo "App should be available at: http://${NODE_IP}:30004"
            }
        }
    }
}
