apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-infer-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-infer
  template:
    metadata:
      labels:
        app: mlops-infer
    spec:
      containers:
        - name: mlops-infer-container
          image: vamshiadep21/mlops-infer:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
