apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlops-infer-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: mlops.local  
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mlops-infer-service
                port:
                  number: 8000
